### ISSUE TITLE
TestLocalResourcesTrackerImpl.testLocalResourceCache fails occasionally

### ISSUE THREAD

**Issue by steffengr** [hopshadoop/hops#11]
TestLocalResourcesTrackerImpl.testLocalResourceCache fails occasionally on Jenkins and hence lets the build fail.

See [Jenkins](https://cloud17.sics.se/jenkins/job/hops-develop/io.hops$hadoop-yarn-server-nodemanager/20/testReport/org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer/TestLocalResourcesTrackerImpl/testLocalResourceCache/).

**Comment by berthoug** [comment]
I cannot reproduce the bug. 
I think it is a race condition: the test check the value before that the event get handled.
