### ISSUE TITLE
[Interface] File upload not auto-starting while interface shows they should

### ISSUE THREAD

**Issue by nicoinn** [hopshadoop/hops#318]
In the web interface, after selecting a file to upload, the pop-up window shows a "pause" button suggesting that the file is uploading, but nothing happens.

![Bug](https://s30.postimg.org/50mkvtd41/Screen_Shot_2017_01_02_at_17_03_43.png)

The upload needs to be started manually by doing "pause/play" near the file or "Upload all". Everything works fine after that. 

A quick fix would be to simply show the "play" button instead of "pause" after returning from the select file windows to avoid confusing the user :)

**Comment by tkakantousis** [comment]
https://github.com/hopshadoop/hopsworks/pull/670
