### ISSUE TITLE
[Zeppelin] Third layer characters not recognised under Chrome

### ISSUE THREAD

**Issue by nicoinn** [hopshadoop/hops#319]
Symptom: Impossible to type "[" or "]" on Mac using Google Chrome and keyboard layout set to Belgian. 
By extension, all characters accessed by Alt+Shift+...  are not recognised. 

The problem does not appear in Safari.

**Comment by jimdowling** [comment]
Thanks for reporting it, but I'm going to close this as a Zeppelin Issue (not a Hopsworks issue) that we won't fix.
