### ISSUE TITLE
the leader does not guaranty that there won't be two leaders at the same time

### ISSUE THREAD

**Issue by berthoug** [hopshadoop/hops#99]
Some logs suggest that a node can loose its leader status while it manage to update its counter less than 2*hbPeriod before the lost:

**Node1:**
>15/12/16 06:49:42 DEBUG [Thread-8] (LeaderElection.java:run(76))   - LE Status: id 1 Leader Election Start Round. Time period 1000 Time since last update 1001
15/12/16 06:49:42 DEBUG [Thread-8] (LeaderElection.java:run(132))   - LE Status: id 1 Leader Election End Round. Update time was 6 ms
15/12/16 06:49:43 DEBUG [Thread-8] (LeaderElection.java:run(76))   - LE Status: id 1 Leader Election Start Round. Time period 1000 Time since last update 1002
15/12/16 06:49:45 ERROR [Thread-8] (LeaderElection.java:run(126))   - LE Status: id 1 LeaderElection: Update Tx took very long time to update: 1646, time_perid is 1000
15/12/16 06:49:45 DEBUG [Thread-8] (LeaderElection.java:run(132))   - LE Status: id 1 Leader Election End Round. Update time was 1646 ms
15/12/16 06:49:45 DEBUG [Thread-8] (LeaderElection.java:run(76))   - LE Status: id 1 Leader Election Start Round. Time period 1000 Time since last update 7
**15/12/16 06:49:45 DEBUG [Thread-8] (LeaderElection.java:run(132))   - LE Status: id 1 Leader Election End Round. Update time was 10 ms
15/12/16 06:49:46 DEBUG [Thread-8] (LeaderElection.java:run(76))   - LE Status: id 1 Leader Election Start Round. Time period 1000 Time since last update 1005
15/12/16 06:49:46  INFO [Thread-8] (LETransaction.java:leaderCheck(257))  LEADER_ELECTION - LE Status: id 3 I am a NON_LEADER process 
15/12/16 06:49:46 DEBUG [Thread-8] (LeaderElection.java:run(132))   - LE Status: id 3 Leader Election End Round. Update time was 6 ms**
15/12/16 06:49:47 DEBUG [Thread-8] (LeaderElection.java:run(76))   - LE Status: id 3 Leader Election Start Round. Time period 1000 Time since last update 1002
15/12/16 06:49:47 DEBUG [Thread-8] (LeaderElection.java:run(132))   - LE Status: id 3 Leader Election End Round. Update time was 7 ms
15/12/16 06:49:48 DEBUG [Thread-8] (LeaderElection.java:run(76))   - LE Status: id 3 Leader Election Start Round. Time period 1000 Time since last update 1002
15/12/16 06:49:48 DEBUG [Thread-8] (LeaderElection.java:run(132))   - LE Status: id 3 Leader Election End Round. Update time was 7 ms

**Node2:**
>15/12/16 06:49:46 DEBUG [Thread-8] (LeaderElection.java:run(76))   - LE Status: id 2 Leader Election Start Round. Time period 1000 Time since last update 1002
15/12/16 06:49:46 DEBUG [Thread-8] (LeaderElection.java:run(132))   - LE Status: id 2 Leader Election End Round. Update time was 7 ms
**15/12/16 06:49:47 DEBUG [Thread-8] (LeaderElection.java:run(76))   - LE Status: id 2 Leader Election Start Round. Time period 1000 Time since last update 1003
15/12/16 06:49:47  WARN [Thread-8] (LETransaction.java:leaderCheck(250))  LEADER_ELECTION - LE Status: id 2 I can be the leader but I have weak locks. Retry with stronger lock
15/12/16 06:49:47  WARN [Thread-8] (LETransaction.java:periodicUpdate(156))  LEADER_ELECTION - LE Status: id 2 periodic update. Stronger locks requested in next round
15/12/16 06:49:47 DEBUG [Thread-8] (LeaderElection.java:run(132))   - LE Status: id 2 Leader Election End Round. Update time was 8 ms
15/12/16 06:49:47 DEBUG [Thread-8] (LeaderElection.java:run(76))   - LE Status: id 2 Leader Election Start Round. Time period 1000 Time since last update 2
15/12/16 06:49:47  INFO [Thread-8] (LETransaction.java:leaderCheck(243))  LEADER_ELECTION - LE Status: id 2 I am the new LEADER. 
15/12/16 06:49:47 DEBUG [Thread-8] (LETransaction.java:removeDeadNameNodes(290))  LEADER_ELECTION - LE Status: id 2 removing dead node 1
15/12/16 06:49:47 DEBUG [Thread-8] (LeaderElection.java:run(132))   - LE Status: id 2 Leader Election End Round. Update time was 7 ms**
15/12/16 06:49:48 DEBUG [Thread-8] (LeaderElection.java:run(76))   - LE Status: id 2 Leader Election Start Round. Time period 1000 Time since last update 1002
15/12/16 06:49:48 DEBUG [Thread-8] (LeaderElection.java:run(132))   - LE Status: id 2 Leader Election End Round. Update time was 12 ms
15/12/16 06:49:49 DEBUG [Thread-8] (LeaderElection.java:run(76))   - LE Status: id 2 Leader Election Start Round. Time period 1000 Time since last update 1003
15/12/16 06:49:49 DEBUG [Thread-8] (LeaderElection.java:run(132))   - LE Status: id 2 Leader Election End Round. Update time was 27 ms

(The nodes clock may not be exactly in sync)

**Comment by smkniazi** [comment]
From the logs it is clear that Yarn voluntarily relinquished the leader role

**Comment by smkniazi** [comment]
15/12/16 06:49:44 DEBUG [Thread-9] (ResourceManager.java:transitionToStandby(976))   - Transitioning to standby bbc2-10G/10.0.1.22:2110

**Comment by jimdowling** [comment]
What does this mean? Why would the RM volutnarily relinquish its role as leader?

**Comment by berthoug** [comment]
In this case the update of the database is too slow so the leader lease is lost and the RM loose the leader role and transition to standby. This is what the logs say and this is normal behaviour. 

What the log does not say is that in the transitionToStanby function we force the leader election process to relinquish its id and to get a new one. This was done to give the administrator the possibility to make the leader transition to standby. I can remove it but I'll have to rewrite all the HA tests for this (they use the transitionToStandby admin call to simulate the crash of the scheduler node).

Keeping this is not a problem because once the RM as transitioned to standby it will have to go through a total recovery to become active again, so it has no impact if the new leader is the same RM that kept its id or another node because the previous leader relinquished its id.

**Comment by jimdowling** [comment]
So what's the fix - rewrite the tests or something else?

**Comment by berthoug** [comment]
The problem occurred in a run that was misconfigured: the leader election timeout was lower than the database transaction timeout. Correcting the configuration resolved the problem, but the logs made us thought that there was another problem. We now know that there is no other problem.

**Comment by jimdowling** [comment]
This is a constraint we should fix in the Chef cookbook. What are the two attribute names for the timeouts?

**Comment by berthoug** [comment]
TransactionInactiveTimeout in the database configuration and dfs.leader.check.interval in the hadoop configuration.
fs.leader.check.interval should be superior to TransactionInactiveTimeout.
